service: speee-engineering-test

provider:
  name: aws
  runtime: python3.13
  region: ap-northeast-1

functions:
  app:
    handler: main.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app
  pythonRequirements:
    dockerizePip: non-linux
